FROM althack/ros:noetic-full
# Install dependencies.
RUN apt-get update -qq && apt-get install -y  build-essential \
    ffmpeg libsm6 libxext6 autoconf libtool mesa-utils \
    terminator nano git wget curl iputils-ping \
    libcanberra-gtk-module libcanberra-gtk3-module \
    ros-dev-tools 

RUN apt-get update && apt-get install -y ros-noetic-rqt ros-noetic-rqt-common-plugins

# Speech dependencies
RUN apt-get update && apt-get install ros-noetic-audio-common-msgs
RUN apt-get update && apt-get install -y alsa-base alsa-utils gstreamer-1.0

RUN apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
RUN apt install -y espeak
RUN pip install -U openai-whisper 


RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

RUN mkdir /workspace
WORKDIR /workspace

# Python modules
COPY requirements/nlp.txt /workspace/requirements/nlp.txt
COPY requirements/speech.txt /workspace/requirements/speech.txt

RUN pip install -r requirements/nlp.txt
RUN pip install -r requirements/speech.txt

# Create files to avoid dir creation when mounting volumes
RUN touch /tmp/pulseaudio.socket
RUN touch /tmp/pulseaudio.client.conf

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]