# Speech variables
x-speech-variables: &speech-variables
  KEYWORD_DIR: /workspace/ws/src/speech/scripts/keywords

services:
  speech_processing:
    build:
      # Use context of parent directory (dockerfiles make reference to parent directory)
      context: ..
      dockerfile: docker/Dockerfile.hri.cuda
    volumes:
      - ../ws:/workspace/ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    network_mode: host
    user: ${LOCAL_USER_ID}:${LOCAL_GROUP_ID}
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    environment:
      <<:
        - *speech-variables
      DISPLAY: ${DISPLAY}
    env_file:
      - ../.env
      - network.env
    healthcheck:
      test: ["CMD-SHELL", "rostopic list > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    command:
      [
        "source /workspace/ws/devel/setup.bash && roslaunch hri recepcionist_laptop.launch",
      ]
